### ISSUE TITLE
Test for SBT is quite lengthy

### ISSUE THREAD

**Issue by mjdavies** [ONSdigital/jenkins-build-envs#2]
Because of the way sbt works, when you first run 'sbt version' it has to go and download a lot of data from the internet.

We could move this into the Dockerfile, but that would just make the build take longer as opposed to the test.

It would be good if we had a more elegant solution to this, as currently the tests take a while due to this issue.

Maybe change the method if the test, or change the setup so it takes less time?

Open to ideas

**Comment by willis7** [comment]
So, the following PR adds travis ci. Currently, the build is taking 3 mins to complete - thats make all images and run the version test. For me, thats sufficient. One solution may be to cache dependencies - but then, that isn't strictly a "clean" build.

https://github.com/ONSdigital/jenkins-build-envs/pull/4

**Comment by willis7** [comment]
I've fixed this by running `sbt clean` during the build process. That caches the artifacts of the boot process meaning it doesn't run every time.
